In [4]:
import numpy as np
import pandas as pd

In [17]:
np.random.seed(55)

Creating a random sample data

In [18]:
data = {
        "ID": np.arange (1,11),
        "Category": np.random.choice(['A','B','C'], size=10),
        "Value1": np.random.randint(10,100, size=10),
        "Value2": np.random.uniform(1.0,50.0, size=10)
}
df = pd.DataFrame(data)
print("Initial DataFrame:\n")
df

Initial DataFrame:

   ID Category  Value1     Value2
0   1        B      45  45.030700
1   2        C      56  49.294968
2   3        A      71  25.340501
3   4        B      87  18.263627
4   5        B      22  43.487165
5   6        B      34  20.447206
6   7        B      81  32.539204
7   8        B      41   2.002212
8   9        B      82  40.596143
9  10        C      61  22.051052

In [23]:
df['Sum'] = np.add(df['Value1'], df['Value2']) # Value1 + Value2
df['Difference'] = np.subtract(df['Value1'], df['Value2']) # Value1 - Value2
df['SquareRoot_V1'] = np.sqrt(df['Value1']) # sqrt of Value1
df['Quotient'] = np.divide(df['Value1'], df['Value2'])
df['mean'] = np.mean(df['Value1'])
df['Product'] = np.multiply(df['Value1'], df['Value2'])

print('After Numpy Operations:\n')
df

After Numpy Operations:

,ID,Category,Value1,Value2,Sum,Difference,SquareRoot_V1,Quotient,mean,Product
0,1,B,45,45.030700,90.030700,-0.030700,6.708204,0.999318,58.0,2026.381519
1,2,C,56,49.294968,105.294968,6.705032,7.483315,1.136019,58.0,2760.518180
2,3,A,71,25.340501,96.340501,45.659499,8.426150,2.801839,58.0,1799.175585
3,4,B,87,18.263627,105.263627,68.736373,9.327379,4.763566,58.0,1588.935581
4,5,B,22,43.487165,65.487165,-21.487165,4.690416,0.505896,58.0,956.717624
5,6,B,34,20.447206,54.447206,13.552794,5.830952,1.662819,58.0,695.204988
6,7,B,81,32.539204,113.539204,48.460796,9.000000,2.489305,58.0,2635.675503
7,8,B,41,2.002212,43.002212,38.997788,6.403124,20.477349,58.0,82.090706
8,9,B,82,40.596143,122.596143,41.403857,9.055385,2.019896,58.0,3328.883694
9,10,C,61,22.051052,83.051052,38.948948,7.810250,2.766308,58.0,1345.114160

In [49]:
filtered_df = df[(df['Value1']>50) & (df['Category']=='A')] # Filtering DataFrame

print('Filtered DataFrame (Value1>50 7 Category == A): \n')
filtered_df

Filtered DataFrame (Value1>50 7 Category == A):

   ID Category  Value1    Value2        Sum  Difference  SquareRoot_V1
1   2        A      84  9.909423  93.909423   74.090577       9.165151

In [50]:
grouped = df.groupby('Category').agg({ # grouping and aggregating
    'Value1': ['mean','max','min'],
    'Value2': ['mean', 'sum']
})

print('Grouped and aggregated data: \n')
grouped

Grouped and aggregated data:

             Value1             Value2
               mean max min       mean        sum
Category
A         42.333333  84  12  19.595931  58.787794
B         11.000000  11  11  30.980792  30.980792
C         68.666667  97  33  12.619970  75.719822

In [51]:
df["Value1_Normalized"] = df["Value1"].apply(lambda x: (x - np.min(df["Value1"])) / (np.max(df["Value1"]) - np.min(df["Value1"])))

print("With normalized Value1:\n")
df

With normalized Value1:

,ID,Category,Value1,Value2,Sum,Difference,SquareRoot_V1,Value1_Normalized
0,1,C,84,11.404616,95.404616,72.595384,9.165151,0.848837
1,2,A,84,9.909423,93.909423,74.090577,9.165151,0.848837
2,3,C,97,9.986821,106.986821,87.013179,9.848858,1.000000
3,4,C,33,15.907870,48.907870,17.092130,5.744563,0.255814
4,5,A,12,26.713065,38.713065,-14.713065,3.464102,0.011628
5,6,A,31,22.165306,53.165306,8.834694,5.567764,0.232558
6,7,C,62,15.270228,77.270228,46.729772,7.874008,0.593023
7,8,B,11,30.980792,41.980792,-19.980792,3.316625,0.000000
8,9,C,97,7.835199,104.835199,89.164801,9.848858,1.000000
9,10,C,39,15.315088,54.315088,23.684912,6.244998,0.325581

In [52]:
df.loc[2,'Value1'] = np.nan
df.loc[5,'Value2'] = np.nan

print('With NaN values:\n')
df

With NaN values:

,ID,Category,Value1,Value2,Sum,Difference,SquareRoot_V1,Value1_Normalized
0,1,C,84.0,11.404616,95.404616,72.595384,9.165151,0.848837
1,2,A,84.0,9.909423,93.909423,74.090577,9.165151,0.848837
2,3,C,NaN,9.986821,106.986821,87.013179,9.848858,1.000000
3,4,C,33.0,15.907870,48.907870,17.092130,5.744563,0.255814
4,5,A,12.0,26.713065,38.713065,-14.713065,3.464102,0.011628
5,6,A,31.0,NaN,53.165306,8.834694,5.567764,0.232558
6,7,C,62.0,15.270228,77.270228,46.729772,7.874008,0.593023
7,8,B,11.0,30.980792,41.980792,-19.980792,3.316625,0.000000
8,9,C,97.0,7.835199,104.835199,89.164801,9.848858,1.000000
9,10,C,39.0,15.315088,54.315088,23.684912,6.244998,0.325581